### ISSUE TITLE
Have you had any success getting a fix?

### ISSUE THREAD

**Issue by forficate** [fkettelhoit/cf-worker-rust-hanging-promise#1]
Sorry to raise as a issue. Did you manage to get this resolved?

I think I'm seeing a similar issue.

I have an application which will make a request to my Cloudflare worker, read some results (a list of id's) and then make a request to my Cloudflare worker for each id, so  1:N.

I see the exact same error you report when the bulk requests are made concurrently, "The script will never generate a response.". If I run the requests manually i.e. not bulk in `Promise.all(...)` my worker responds as expected.

On the WASM side each request will generate a promise from using the fetch api.

I'm not seeing much further information on this error and searching lead me to your test case.

**Comment by fkettelhoit** [comment]
Unfortunately I have not been able to resolve the issue. You probably have already seen the topic I created on the Cloudflare community page, right?

https://community.cloudflare.com/t/a-hanging-promise-was-canceled-rust-wasm-worker/282471

As you can see, there has been no reply from Cloudflare so far and to me it looks like a bug on their side that is specific to the combination of using promises and wasm (which is presumably a rather niche use case). So for now I am still waiting for them to look at the issue. Perhaps you could post in the linked thread and mention that the issue affects you as well?

**Comment by nilslice** [comment]
@fkettelhoit - I just responded to your community post: https://community.cloudflare.com/t/a-hanging-promise-was-canceled-rust-wasm-worker/282471/8?u=nilslice

If you have any ideas as to how to better handle the await per-request, please share. Thanks!

**Comment by nilslice** [comment]
by the way, if you're interested, there is a WIP rust bindings project that I'd love to get your feedback on.. https://github.com/nilslice/workers-rs

this isn't currently published to crates.io, but can be used with a git-based path in a Cargo.toml 

also, the repo location will change, so don't rely on it if you do end up trying it out. I'll have an update there soon to apply the same fix I mentioned above.

**Comment by fkettelhoit** [comment]
@nilslice Thanks, with your proposed fix everything works perfectly now!

I see that you have already pushed the change to the template repo, here are two updated PRs for the cloudflare-docs repo that reflect this change:

https://github.com/cloudflare/cloudflare-docs/pull/1986
https://github.com/cloudflare/cloudflare-docs/pull/1902

I will definitely try out your `workers-rs` repo and report back. Very exciting to see that Rust bindings are being actively worked on!

Closing this as fixed.
